project_id = "eiasfrsmacyhkmfbtfhq"

[functions.process-photo]
enabled = true
verify_jwt = false

[functions.generate-report]
enabled = true
verify_jwt = false

[functions.admin-create-user]
enabled = true
verify_jwt = false

[functions.download-photos-zip]
enabled = true
verify_jwt = false

[functions.generate-rdo-report]
enabled = true
verify_jwt = false